from __future__ import annotations
from pathlib import Path

MAX_NEW_FILE_NON_EMPTY_LOC = 1200
BASELINE_LOC: dict[str, int] = {
    "app/__init__.py": 1,
    "app/__main__.py": 15,
    "app/application/auditoria_e2e/__init__.py": 3,
    "app/application/auditoria_e2e/caso_uso.py": 234,
    "app/application/auditoria_e2e/dto.py": 52,
    "app/application/auditoria_e2e/puertos.py": 20,
    "app/application/auditoria_e2e/reglas.py": 192,
    "app/application/base_cuadrantes_service.py": 43,
    "app/application/conflicts_service.py": 47,
    "app/application/delegada_resolution.py": 39,
    "app/application/dto.py": 131,
    "app/application/dtos/__init__.py": 2,
    "app/application/dtos/contexto_operacion.py": 10,
    "app/application/operaciones/__init__.py": 14,
    "app/application/operaciones/auditoria_e2e_operacion.py": 63,
    "app/application/operaciones/confirmacion_pdf_operacion.py": 97,
    "app/application/operaciones/contratos.py": 14,
    "app/application/operaciones/exportacion_pdf_historico_operacion.py": 107,
    "app/application/operaciones/modelos.py": 38,
    "app/application/pending_conflicts.py": 37,
    "app/application/ports/conflicts_repository.py": 18,
    "app/application/ports/db_lock_error_classifier.py": 5,
    "app/application/ports/pdf_puerto.py": 27,
    "app/application/ports/sistema_archivos_puerto.py": 11,
    "app/application/sheets_service.py": 144,
    "app/application/sync.py": 199,
    "app/application/sync_diagnostics.py": 68,
    "app/application/sync_normalization.py": 43,
    "app/application/sync_sheets_use_case.py": 38,
    "app/application/use_cases/__init__.py": 12,
    "app/application/use_cases/alert_engine.py": 108,
    "app/application/use_cases/conflict_resolution_policy.py": 49,
    "app/application/use_cases/grupos_config/__init__.py": 2,
    "app/application/use_cases/grupos_config/use_case.py": 35,
    "app/application/use_cases/health_check.py": 68,
    "app/application/use_cases/personas/__init__.py": 2,
    "app/application/use_cases/personas/use_case.py": 203,
    "app/application/use_cases/retry_sync_use_case.py": 35,
    "app/application/use_cases/solicitudes/__init__.py": 2,
    "app/application/use_cases/solicitudes/confirmacion_pdf_service.py": 43,
    "app/application/use_cases/solicitudes/confirmar_sin_pdf_planner.py": 52,
    "app/application/use_cases/solicitudes/detector_duplicados.py": 74,
    "app/application/use_cases/solicitudes/ensamblador_resultado.py": 17,
    "app/application/use_cases/solicitudes/helpers_puros.py": 30,
    "app/application/use_cases/solicitudes/helpers_puros_2.py": 39,
    "app/application/use_cases/solicitudes/mapping_service.py": 47,
    "app/application/use_cases/solicitudes/normalizacion_solicitud.py": 46,
    "app/application/use_cases/solicitudes/pdf_confirmadas_builder.py": 70,
    "app/application/use_cases/solicitudes/pdf_confirmadas_runner.py": 74,
    "app/application/use_cases/solicitudes/saldos_service.py": 94,
    "app/application/use_cases/solicitudes/use_case.py": 810,
    "app/application/use_cases/solicitudes/validacion_service.py": 95,
    "app/application/use_cases/solicitudes/validaciones.py": 100,
    "app/application/use_cases/solicitudes/validar_datos_basicos.py": 72,
    "app/application/use_cases/sync_sheets/__init__.py": 3,
    "app/application/use_cases/sync_sheets/action_planning.py": 48,
    "app/application/use_cases/sync_sheets/conflict_policy.py": 40,
    "app/application/use_cases/sync_sheets/conflicts.py": 20,
    "app/application/use_cases/sync_sheets/executor.py": 16,
    "app/application/use_cases/sync_sheets/helpers.py": 243,
    "app/application/use_cases/sync_sheets/normalization_rules.py": 8,
    "app/application/use_cases/sync_sheets/payloads_puros.py": 123,
    "app/application/use_cases/sync_sheets/persistence_ops.py": 165,
    "app/application/use_cases/sync_sheets/persona_resolution_rules.py": 11,
    "app/application/use_cases/sync_sheets/planner.py": 6,
    "app/application/use_cases/sync_sheets/pull_planner.py": 46,
    "app/application/use_cases/sync_sheets/pull_runner.py": 36,
    "app/application/use_cases/sync_sheets/push_builder.py": 55,
    "app/application/use_cases/sync_sheets/push_helpers.py": 127,
    "app/application/use_cases/sync_sheets/push_runner.py": 16,
    "app/application/use_cases/sync_sheets/reporting.py": 21,
    "app/application/use_cases/sync_sheets/sync_reporting_rules.py": 47,
    "app/application/use_cases/sync_sheets/sync_sheets_helpers.py": 59,
    "app/application/use_cases/sync_sheets/sync_snapshots.py": 132,
    "app/application/use_cases/sync_sheets/types.py": 20,
    "app/application/use_cases/sync_sheets/use_case.py": 1147,
    "app/application/use_cases/sync_sheets.py": 3,
    "app/application/use_cases/sync_sheets_core.py": 271,
    "app/application/use_cases/validacion_preventiva_lock_use_case.py": 17,
    "app/bootstrap/__init__.py": 1,
    "app/bootstrap/container.py": 87,
    "app/bootstrap/exception_handler.py": 61,
    "app/bootstrap/logging.py": 187,
    "app/bootstrap/settings.py": 25,
    "app/configuracion/__init__.py": 1,
    "app/configuracion/calidad.py": 25,
    "app/core/errors.py": 15,
    "app/core/metrics.py": 49,
    "app/core/observability.py": 74,
    "app/core/redactor_secretos.py": 49,
    "app/domain/base_cuadrantes.py": 16,
    "app/domain/models.py": 69,
    "app/domain/ports.py": 171,
    "app/domain/request_time.py": 70,
    "app/domain/services.py": 102,
    "app/domain/sheets_errors.py": 14,
    "app/domain/sync_models.py": 167,
    "app/domain/time_range.py": 37,
    "app/domain/time_utils.py": 51,
    "app/entrypoints/__init__.py": 1,
    "app/entrypoints/cli_auditoria.py": 46,
    "app/entrypoints/main.py": 57,
    "app/entrypoints/ui_main.py": 53,
    "app/infrastructure/auditoria_e2e/__init__.py": 2,
    "app/infrastructure/auditoria_e2e/adaptadores.py": 48,
    "app/infrastructure/conflicts_payloads.py": 145,
    "app/infrastructure/db.py": 29,
    "app/infrastructure/health_probes.py": 150,
    "app/infrastructure/local_config.py": 62,
    "app/infrastructure/local_config_store.py": 5,
    "app/infrastructure/migrations.py": 237,
    "app/infrastructure/migrations_cli.py": 4,
    "app/infrastructure/pdf/generador_pdf_reportlab.py": 42,
    "app/infrastructure/repos_conflicts_sqlite.py": 343,
    "app/infrastructure/repos_sqlite.py": 500,
    "app/infrastructure/repos_sqlite_builders.py": 157,
    "app/infrastructure/repos_sqlite_personas.py": 201,
    "app/infrastructure/seed.py": 175,
    "app/infrastructure/sheets_client.py": 289,
    "app/infrastructure/sheets_client_puros.py": 57,
    "app/infrastructure/sheets_errors.py": 76,
    "app/infrastructure/sheets_gateway_gspread.py": 71,
    "app/infrastructure/sheets_gateway_puros.py": 88,
    "app/infrastructure/sheets_repository.py": 40,
    "app/infrastructure/sheets_sync_service.py": 2,
    "app/infrastructure/sistema_archivos/__init__.py": 2,
    "app/infrastructure/sistema_archivos/local.py": 26,
    "app/infrastructure/sqlite_lock_error_classifier.py": 6,
    "app/infrastructure/sqlite_uow.py": 26,
    "app/infrastructure/sync_sheets_adapter.py": 61,
    "app/infrastructure/sync_sheets_adapter_puros.py": 28,
    "app/pdf/pdf_builder.py": 279,
    "app/pdf/service.py": 8,
    "app/ui/componentes/badge_estado.py": 12,
    "app/ui/componentes/botones.py": 10,
    "app/ui/componentes/dialogos.py": 8,
    "app/ui/componentes/tarjeta.py": 10,
    "app/ui/components/__init__.py": 7,
    "app/ui/components/card_widget.py": 16,
    "app/ui/components/contexto_trabajo_widget.py": 41,
    "app/ui/components/empty_state.py": 49,
    "app/ui/components/primary_button.py": 7,
    "app/ui/components/saldos_card.py": 194,
    "app/ui/components/secondary_button.py": 7,
    "app/ui/components/status_badge.py": 21,
    "app/ui/conflict_guidance.py": 44,
    "app/ui/conflicts_dialog.py": 331,
    "app/ui/controladores/controlador_navegacion.py": 10,
    "app/ui/controladores/controlador_sincronizacion.py": 4,
    "app/ui/controladores/controlador_solicitudes.py": 4,
    "app/ui/controladores/main_window_controlador.py": 18,
    "app/ui/controllers/pdf_controller.py": 6,
    "app/ui/controllers/personas_controller.py": 13,
    "app/ui/controllers/solicitudes_controller.py": 189,
    "app/ui/controllers/sync_button_state_rules.py": 160,
    "app/ui/controllers/sync_controller.py": 152,
    "app/ui/copy_catalog.py": 76,
    "app/ui/dialog_opciones.py": 213,
    "app/ui/dialogos_comunes.py": 50,
    "app/ui/error_mapping.py": 48,
    "app/ui/estado/estado_main_window.py": 6,
    "app/ui/estilos/apply_theme.py": 5,
    "app/ui/estilos/tokens.py": 14,
    "app/ui/group_dialog.py": 188,
    "app/ui/historico_view.py": 212,
    "app/ui/main_window.py": 51,
    "app/ui/models/solicitudes_table_presenter.py": 80,
    "app/ui/models_qt.py": 196,
    "app/ui/notification_service.py": 245,
    "app/ui/patterns.py": 37,
    "app/ui/person_dialog.py": 258,
    "app/ui/style.py": 44,
    "app/ui/sync_reporting.py": 444,
    "app/ui/theme/__init__.py": 9,
    "app/ui/theme/cgt_theme.py": 10,
    "app/ui/toast_compat.py": 82,
    "app/ui/toast_helpers.py": 25,
    "app/ui/vistas/builders/main_window_builders.py": 795,
    "app/ui/vistas/confirmacion_actions.py": 436,
    "app/ui/vistas/confirmacion_presenter.py": 114,
    "app/ui/vistas/confirmar_pdf_state.py": 3,
    "app/ui/vistas/historico_actions.py": 288,
    "app/ui/vistas/historico_filter_rules.py": 106,
    "app/ui/vistas/historico_refresh_logic.py": 13,
    "app/ui/vistas/init_refresh.py": 13,
    "app/ui/vistas/main_window/__init__.py": 11,
    "app/ui/vistas/main_window/acciones_pendientes.py": 247,
    "app/ui/vistas/main_window/acciones_personas.py": 256,
    "app/ui/vistas/main_window/acciones_sincronizacion.py": 175,
    "app/ui/vistas/main_window/acciones_sincronizacion_resultados.py": 211,
    "app/ui/vistas/main_window/data_refresh.py": 120,
    "app/ui/vistas/main_window/dialogos_sincronizacion.py": 207,
    "app/ui/vistas/main_window/form_handlers.py": 95,
    "app/ui/vistas/main_window/layout_builder.py": 146,
    "app/ui/vistas/main_window/state_controller.py": 1117,
    "app/ui/vistas/main_window/validacion_preventiva.py": 259,
    "app/ui/vistas/main_window/wiring.py": 10,
    "app/ui/vistas/main_window_health_mixin.py": 93,
    "app/ui/vistas/main_window_helpers.py": 236,
    "app/ui/vistas/main_window_vista.py": 46,
    "app/ui/vistas/paginas/pagina_configuracion.py": 18,
    "app/ui/vistas/paginas/pagina_historico.py": 20,
    "app/ui/vistas/paginas/pagina_personas.py": 7,
    "app/ui/vistas/paginas/pagina_sincronizacion.py": 20,
    "app/ui/vistas/paginas/pagina_solicitudes.py": 19,
    "app/ui/vistas/pendientes_iter_presenter.py": 60,
    "app/ui/vistas/pending_duplicate_presenter.py": 65,
    "app/ui/vistas/personas_presenter.py": 64,
    "app/ui/vistas/solicitudes_presenter.py": 107,
    "app/ui/vistas/solicitudes_ux_rules.py": 34,
    "app/ui/vistas/ui_helpers.py": 8,
    "app/ui/widgets/buttons.py": 3,
    "app/ui/widgets/time_edit.py": 48,
    "app/ui/widgets/toast.py": 436,
    "app/ui/workers/sincronizacion_workers.py": 37,
}

def _count_non_empty_lines(path: Path) -> int:
    return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.strip())

def test_no_new_monolith_files_in_app() -> None:
    oversized_new_files: list[tuple[str, int]] = []

    for path in sorted(Path("app").rglob("*.py")):
        relative = path.as_posix()
        if relative in BASELINE_LOC:
            continue
        loc = _count_non_empty_lines(path)
        if loc > MAX_NEW_FILE_NON_EMPTY_LOC:
            oversized_new_files.append((relative, loc))

    assert not oversized_new_files, (
        "Se detectaron nuevos monolitos en app/ (> 1200 LOC no vacías): "
        + ", ".join(f"{file_path} ({loc})" for file_path, loc in oversized_new_files)
    )
