from __future__ import annotations

"""Catálogo centralizado de textos de interfaz.

Este módulo evita strings duplicados en widgets y facilita mantenimiento de copy.
Regla práctica para juniors:
- Usa claves estables por subcontexto (ej. ``solicitudes.*``).
- No referencies textos desde la UI de forma hardcoded.
- Si cambias un mensaje, conserva la clave y solo ajusta el valor.
"""

_COPY: dict[str, str] = {
    # Solicitudes
    "solicitudes.section_title": "Solicitudes",
    "solicitudes.subtitle": "Gestiona la operativa diaria de solicitudes con una vista clara y consistente.",
    "solicitudes.form_section_title": "Datos de la reserva",
    "solicitudes.label_delegada": "Delegada",
    "solicitudes.label_fecha": "Fecha",
    "solicitudes.label_desde": "Desde",
    "solicitudes.label_hasta": "Hasta",
    "solicitudes.label_notas": "Notas",
    "solicitudes.placeholder_notas": "Notas para la solicitud",
    "solicitudes.button_add_pending": "Añadir pendiente",
    "solicitudes.button_update_pending": "Actualizar pendiente",
    "solicitudes.button_confirm_without_pdf": "Confirmar sin PDF",
    "solicitudes.button_confirm_with_pdf": "Confirmar y generar PDF",
    "solicitudes.button_pending_delete": "Eliminar selección",
    "solicitudes.pending_errors_title": "Revisa estos puntos antes de continuar",
    "solicitudes.pending_errors_intro": "Falta completar algunos datos. Te indicamos cómo resolverlo:",
    "solicitudes.tooltip_delegada": "Selecciona la delegada para asociar correctamente la solicitud.",
    "solicitudes.tooltip_fecha": "Elige la fecha del permiso sindical que vas a registrar.",
    "solicitudes.tooltip_desde": "Hora de inicio. Ejemplo: 09:00.",
    "solicitudes.tooltip_hasta": "Hora de fin. Debe ser posterior a la hora de inicio.",
    "solicitudes.tooltip_minutos": "Duración calculada automáticamente en formato HH:MM.",
    "solicitudes.tooltip_notas": "Opcional: añade contexto para recordar el motivo.",
    "solicitudes.tip_enter": "Tip: pulsa Enter para guardar más rápido.",
    "solicitudes.tip_minutes": "Tip: 90 minutos equivalen a 1h 30min.",
    "solicitudes.tip_full_day": "Tip: marca 'Completo' cuando sea un día completo.",
    "solicitudes.help_toggle": "Mostrar ayuda",
    "solicitudes.status_ready": "Listo",
    "solicitudes.status_saved": "Guardado",
    "solicitudes.status_pending_sync": "Pendiente de sync",
    "solicitudes.status_error": "Error",
    "solicitudes.status_pending_sync_hint": "Hay cambios guardados localmente que aún no se han enviado a Google Sheets.",
    "solicitudes.validation_delegada": "Falta delegada. Selecciona una para continuar.",
    "solicitudes.validation_fecha": "Fecha inválida. Revisa el día seleccionado.",
    "solicitudes.validation_tramo_prefix": "Tramo horario incompleto.",
    "solicitudes.validation_conflict": "Ya existe un conflicto pendiente en esa fecha. Ajusta fecha o tramo.",
    "solicitudes.validation_blocking_toast": "Revisa los errores marcados y corrígelos para continuar.",
    "solicitudes.no_aplica_completo": "No aplica en solicitud completa",
    "solicitudes.confirm_delete_pending_title": "Confirmar eliminación",
    "solicitudes.confirm_delete_pending_message": "Se eliminará la solicitud pendiente seleccionada. ¿Deseas continuar?",
    "pendientes.toast_undo": "Pendiente deshecha",
    # Sync credenciales
    "sync_credenciales.title": "Asistente de conexión con Google Sheets",
    "sync_credenciales.step_1": "Paso 1 · Qué necesitas",
    "sync_credenciales.step_1_body": "Necesitas el ID/URL de la hoja y un archivo JSON de credenciales de cuenta de servicio.",
    "sync_credenciales.step_2": "Paso 2 · Cargar credenciales",
    "sync_credenciales.step_3": "Paso 3 · Probar conexión",
    "sync_credenciales.step_4": "Paso 4 · Guardar y finalizar",
    "sync_credenciales.spreadsheet_placeholder": "Pega aquí la URL o el ID de la hoja",
    "sync_credenciales.credentials_button": "Seleccionar credenciales JSON…",
    "sync_credenciales.test_connection": "Probar conexión",
    "sync_credenciales.save": "Guardar",
    "sync_credenciales.saved_ok": "Configuración guardada. Ya puedes sincronizar.",
    "sync_credenciales.status_pending": "Pendiente de comprobación",
    "sync_credenciales.status_ok": "Conexión verificada",
    "sync_credenciales.status_credentials_missing": "Credenciales sin seleccionar",
    "sync_credenciales.status_credentials_ok": "Credenciales seleccionadas",
    "sync_credenciales.status_sheet_missing": "Hoja sin configurar",
    "sync_credenciales.status_sheet_ok": "Hoja configurada",
    # UI preferencias
    "ui.preferencias.settings_show_help_key": "ux/mostrar_ayuda",
    "ui.preferencias.saldos_detallados": "Saldos detallados",
    "ui.preferencias.cerrar": "Cerrar",
    "ui.preferencias.confirmacion": "Confirmación",
    "ui.preferencias.solicitudes_confirmadas": "solicitudes confirmadas",
    "ui.preferencias.errores": "errores",
    "ui.preferencias.no_confirmada": "No se pudo confirmar ninguna solicitud",
    "ui.preferencias.validacion_preventiva": "Validación preventiva",
    "ui.preferencias.corregir_errores": "Corrige los errores pendientes antes de añadir.",
    "ui.preferencias.mensual": "Mensual",
    # UI sync
    "ui.sync.preferencias": "Preferencias",
    "ui.sync.maximizada_por_defecto": "Abrir la app maximizada por defecto",
    "ui.sync.google_sheets": "Google Sheets",
    "ui.sync.fuente_placeholder": "Fuente: --",
    "ui.sync.rango_placeholder": "Rango: --",
    "ui.sync.configurar_conexion": "Configurar conexión Google Sheets",
    "ui.sync.probar_conexion": "Probar conexión",
    "ui.sync.sincronizar_ahora": "Sincronizar ahora",
    "ui.sync.configuracion": "Configuración",
    "ui.sync.resumen": "Resumen de sincronización con acciones rápidas. El detalle técnico está en modo avanzado.",
    "ui.sync.estado": "Estado",
    "ui.sync.ultima_sync_placeholder": "Última sync: --",
    "ui.sync.estado_pendiente": "Estado: Pendiente",
    "ui.sync.acciones": "Acciones",
    "ui.sync.simular": "Simular sincronización",
    "ui.sync.reintentar_fallidos": "Reintentar solo fallidos",
    "ui.sync.ver_detalles": "Ver detalles",
    "ui.sync.ocultar_detalles": "Ocultar detalles",
    "ui.sync.copiar_informe": "Copiar informe",
    "ui.sync.abrir_logs": "Abrir carpeta de logs",
    "ui.sync.ver_historial": "Ver historial",
    "ui.sync.revisar_conflictos": "Revisar conflictos",
    "ui.sync.metricas_placeholder": "Duración: -- · Cambios: -- · Conflictos: -- · Errores: --",
    "ui.sync.tendencia_placeholder": "Tendencia (5): --",
    "ui.sync.idempotencia_placeholder": "Evita duplicados: --",
    "ui.sync.resumen_conteos_placeholder": "Resumen: creadas 0 · actualizadas 0 · omitidas 0 · conflictos 0 · errores 0",
    "ui.sync.ir_configuracion": "Ir a configuración",
    "ui.sync.sincronizando": "Sincronizando con Google Sheets…",
    "ui.sync.alertas_sin_activas": "Alertas: sin alertas activas.",
    "ui.sync.conflictos_pendientes": "Hay 0 conflictos pendientes de revisión.",
    "ui.sync.resultado_resumido": "Resultado resumido",
    "ui.sync.panel_avanzado": "Panel avanzado",
    "ui.sync.detalles_tecnicos": "Detalles técnicos",
    "ui.sync.salud_sistema": "Salud del sistema",
    "ui.sync.estado_general_pendiente": "Estado general: pendiente de comprobación",
    "ui.sync.columna_categoria": "Categoría",
    "ui.sync.columna_accion": "Acción",
    "ui.sync.actualizar_salud": "Actualizar salud",
    "ui.sync.no_mostrar_hoy": "No mostrar hoy",
    "ui.sync.tab_sincronizacion": "Sincronización",
    "ui.sync.pendiente_horas": "Pendiente: 00:00",
    "ui.sync.fuente_prefix": "Fuente:",
    "ui.sync.rango_prefix": "Rango:",
    "ui.sync.idempotencia_regla": "Evita duplicados: misma delegada, fecha y tramo",
    "ui.sync.window_title": "Horas Sindicales",
    "ui.sync.qt_no_disponible": "UI no disponible: falta instalación de Qt/PySide6",
    "ui.sync.mainwindow_incompleta": "MainWindow mal inicializada. Falta widget requerido:",
    # UI conflictos
    "ui.conflictos.accion_recomendada_label": "Acción recomendada:",
    "ui.conflictos.solicitud_label": "Solicitud:",
    "ui.conflictos.item_accion_recomendada": "- Acción recomendada:",
    "ui.conflictos.item_delegada_afectada": "- Delegada afectada:",
    "ui.conflictos.item_tipo_conflicto": "- Tipo de conflicto:",
    "ui.conflictos.estado_con_avisos": "· Con avisos",
    "ui.conflictos.estado_pendiente": "· Pendiente",
    "ui.sync.resumen_actualizadas": "Actualizadas en Sheets:",
    "ui.sync.resumen_insertadas": "Insertadas en Sheets:",
    "ui.sync.resumen_omitidas_delegada": "Omitidas por delegada:",
    "ui.sync.resumen_duplicados_omitidos": "Duplicados omitidos:",
    "ui.sync.resumen_conflictos": "Conflictos:",
    "ui.sync.resumen_errores": "Errores:",
    "ui.sync.resumen_ultima_sincronizacion": "Última sincronización:",
    "ui.sync.bullet_conflictos": "· Conflictos:",
    "ui.sync.bullet_errores": "· Errores:",
    "ui.sync.bullet_filas_actualizadas": "· Filas actualizadas:",
    "ui.sync.bullet_filas_omitidas": "· Filas omitidas:",
    "ui.sync.detalles_sincronizacion": "Detalles de sincronización",
    "ui.sync.columna_accion_sugerida": "Acción sugerida",
    "ui.sync.columna_entidad": "Entidad",
    "ui.sync.columna_mensaje": "Mensaje",
    "ui.sync.columna_seccion": "Sección",
    "ui.sync.columna_sev": "Sev",
    "ui.sync.columna_timestamp": "Timestamp",
    "ui.sync.abrir_solicitud_afectada": "Abrir solicitud afectada",
    "ui.sync.marcar_para_revision": "Marcar para revisión",
    "ui.sync.reintentar_solo_fallidos": "Reintentar solo fallidos",
    "ui.sync.exportar_detalle": "Exportar detalle",
    "ui.sync.abrir_detalle": "Abrir detalle",
    "ui.sync.estado_en_espera": "⏸ En espera",
    "ui.sync.estado_pendiente_sincronizando": "🕒 Pendiente · Sincronizando",
    "ui.sync.estado_error_config_incompleta": "⛔ Error · Configuración incompleta",
    "ui.sync.error_configura_credenciales": "Error: configura credenciales de Google Sheets",
    "ui.sync.sin_archivo": "sin archivo",
    "ui.sync.spreadsheet_label": "Spreadsheet",
    "ui.sync.bullet_credencial": "· credencial",
    "ui.sync.sincronizacion_completa": "Sincronización completa de delegadas y solicitudes.",
    "ui.sync.delegada_no_seleccionada": "Delegada no seleccionada",
    "ui.sync.nunca": "Nunca",
    "ui.sync.fuente_label": "Fuente:",
    "ui.sync.rango_label": "Rango:",
    "ui.sync.evita_duplicados_label": "Evita duplicados:",
    "ui.sync.resumen_filas": "Resumen",
    "ui.sync.filas_creadas_label": "Filas creadas:",
    "ui.sync.estado_intento_actual_final": "Estado: intento #{intento} · actual {actual} · final {final}",
    "ui.sync.duracion_label": "Duración:",
    "ui.sync.ms": "ms",
    "ui.sync.cambios_label": "Cambios:",
    "ui.sync.revisar_conflictos_sin_pendientes": "Revisar conflictos (sin pendientes)",
    "ui.sync.historico": "Histórico",
    "ui.sync.historico_sincronizaciones": "Histórico de sincronizaciones",
    "ui.sync.columna_archivo": "Archivo",
    "ui.sync.columna_estado": "Estado",
    "ui.sync.columna_intentos": "Intentos",
    "ui.sync.columna_sync_id": "Sync ID",
    "ui.sync.insertadas_local_label": "Insertadas en local:",
    "ui.sync.actualizadas_local_label": "Actualizadas en local:",
    "ui.sync.no_hay_historico": "No hay sincronizaciones históricas disponibles.",
    "ui.sync.registro_marcado_revision_manual": "Registro marcado para revisión manual.",
    # UI sync report
    "ui.sync_report.warning_solicitudes_existian": "{cantidad} solicitudes ya existían y no cambiaron.",
    "ui.sync_report.warning_filas_omitidas_delegada": "{cantidad} filas omitidas por filtro de delegada.",
    "ui.sync_report.error_solicitudes_sincronizacion": "Error en {cantidad} solicitudes durante la sincronización.",
    "ui.sync_report.conflictos_detectados": "Se detectaron {cantidad} conflictos.",
    "ui.sync_report.idempotency_criteria": "Una solicitud por delegada, fecha y tramo.",
    "ui.sync_report.items_changed_local": "Local: +{created} / ~{updated}",
    "ui.sync_report.items_changed_sheets": "Sheets: +{created} / ~{updated}",
    "ui.sync_report.section_operacion": "Operación",
    "ui.sync_report.entity_config": "Config",
    "ui.sync_report.error_falta_config": "Falta configuración de Google Sheets (Spreadsheet ID o credenciales).",
    "ui.sync_report.sugerencia_ir_config": "Ir a configuración y completar los campos obligatorios.",
    "ui.sync_report.error_config_incompleta": "Configuración incompleta.",
    "ui.sync_report.section_errores": "Errores",
    "ui.sync_report.entity_red": "Red",
    "ui.sync_report.sugerencia_revisar_config_red": "Revisa configuración o red. Reintenta solo fallidos.",
    "ui.sync_report.entity_sync": "Sync",
    "ui.sync_report.sin_detalle_adicional": "Sin detalle adicional.",
    "ui.sync_report.section_creaciones": "Creaciones",
    "ui.sync_report.entity_solicitud": "Solicitud",
    "ui.sync_report.solicitud_nueva": "{uuid}: Solicitud nueva",
    "ui.sync_report.section_actualizaciones": "Actualizaciones",
    "ui.sync_report.solicitud_cambios": "{uuid}: {cantidad} campo(s) con cambios.",
    "ui.sync_report.section_diff": "Diff",
    "ui.sync_report.diff_line": "{uuid} | {field} | actual: {current_value} | nuevo: {new_value}",
    "ui.sync_report.section_conflictos": "Conflictos",
    "ui.sync_report.sugerencia_revisar_conflicto": "Revisa el conflicto y vuelve a sincronizar.",
    "ui.sync_report.section_validaciones": "Validaciones",
    "ui.sync_report.entity_sync_planner": "SyncPlanner",
    "ui.sync_report.sugerencia_corregir_dato": "Corregir dato y volver a simular.",
    "ui.sync_report.no_hay_cambios": "No hay cambios que aplicar.",
    "ui.sync_report.idempotency_simulacion": "Plan inmutable generado por SyncPlanner antes de ejecutar SyncExecutor.",
    "ui.sync_report.simulacion_sin_escritura": "Simulación sin escritura en Google Sheets.",
    "ui.sync_report.timestamp_format": "%Y%m%d_%H%M%S",
    "ui.sync_report.md_titulo_informe": "# Informe de sincronización",
    "ui.sync_report.md_estado": "- Estado: **{estado}**",
    "ui.sync_report.md_inicio": "- Inicio: {inicio}",
    "ui.sync_report.md_fin": "- Fin: {fin}",
    "ui.sync_report.md_duracion": "- Duración: {duracion_ms} ms",
    "ui.sync_report.md_actor": "- Actor: {actor}",
    "ui.sync_report.md_fuente": "- Fuente: {fuente}",
    "ui.sync_report.md_alcance": "- Alcance: {alcance}",
    "ui.sync_report.md_idempotencia": "- Idempotencia: {idempotencia}",
    "ui.sync_report.seccion_resumen": "## Resumen",
    "ui.sync_report.md_solicitudes_creadas": "- Solicitudes creadas: {cantidad}",
    "ui.sync_report.md_solicitudes_actualizadas": "- Solicitudes actualizadas: {cantidad}",
    "ui.sync_report.md_solicitudes_omitidas": "- Solicitudes omitidas (sin cambios): {cantidad}",
    "ui.sync_report.md_conflictos_detectados": "- Conflictos detectados: {cantidad}",
    "ui.sync_report.md_errores": "- Errores: {cantidad}",
    "ui.sync_report.md_solicitudes_locales_totales": "- Solicitudes locales totales: {cantidad}",
    "ui.sync_report.md_solicitudes_remotas_revisadas": "- Solicitudes remotas revisadas: {cantidad}",
    "ui.sync_report.md_llamadas_api": "- Llamadas API: {cantidad}",
    "ui.sync_report.md_reintentos": "- Reintentos: {cantidad}",
    "ui.sync_report.md_conflictos_metrica": "- Conflictos (métrica): {cantidad}",
    "ui.sync_report.md_errores_metrica": "- Errores (métrica): {cantidad}",
    "ui.sync_report.md_tasa_exito": "- Tasa de éxito: {tasa:.0%}",
    "ui.sync_report.seccion_detalle": "## Detalle",
    "ui.sync_report.md_detalle_entry": "- [{timestamp}] **{severity}** · {section}/{entity}: {message}",
    "ui.sync_report.md_detalle_accion": ". Acción: {accion}",
    "ui.sync_report.glob_json": "*.json",
    "ui.sync_report.no_disponible_abrev": "N/D",
    "ui.sync_report.sincronizacion_finalizada": "Sincronización finalizada.",
    "ui.sync_report.section_cambios_aplicados": "Cambios aplicados",
    "ui.sync_report.cambios_aplicados_resumen": "Local +{inserted_local}/~{updated_local}; Sheets +{inserted_remote}/~{updated_remote}.",
    "ui.sync_report.sugerencia_revisar_filtros": "Revisar filtros y confirmar si el comportamiento era esperado.",
    "ui.sync_report.sugerencia_abrir_solicitudes": "Abre las solicitudes afectadas y revísalas.",
    "ui.sync_report.sugerencia_reintentar_fallidos": "Reintentar solo fallidos.",
    "ui.conflictos.tipo_error_acceso": "Error de acceso",
    "ui.conflictos.tipo_diferencia_saldo": "Diferencia de saldo",
    "ui.conflictos.tipo_duplicado_remoto": "Duplicado remoto",
    "ui.conflictos.tipo_solicitud_ya_modificada": "Solicitud ya modificada",
    "ui.conflictos.revisar_manualmente": "Revisar manualmente",
    "ui.conflictos.mantener_local": "Mantener local",
    "ui.conflictos.tipo_label": "Tipo:",
    "ui.conflictos.delegada_afectada_label": "Delegada afectada:",
    "ui.conflictos.why_duplicado_remoto": "La solicitud llegó dos veces desde la nube o en un reintento.",
    "ui.conflictos.why_diferencia_saldo": "Los minutos u horas disponibles no coinciden entre este equipo y la nube.",
    "ui.conflictos.why_solicitud_ya_modificada": "La solicitud cambió en ambos lados antes de terminar la sincronización.",
    "ui.conflictos.why_error_acceso": "No fue posible validar correctamente un dato remoto por permisos o acceso.",
    "ui.conflictos.why_por_defecto": "La solicitud cambió en momentos distintos y requiere decisión.",
    "ui.conflictos.titulo_resolver": "Resolver conflictos de sincronización",
    "ui.conflictos.conflictos_detectados": "Conflictos detectados",
    "ui.conflictos.sin_conflictos_pendientes": "Sin conflictos pendientes.",
    "ui.conflictos.que_paso": "Qué pasó",
    "ui.conflictos.por_que_puede_haber_ocurrido": "Por qué puede haber ocurrido",
    "ui.conflictos.opciones_para_conflicto": "Opciones para este conflicto",
    "ui.conflictos.aceptar_remoto": "Aceptar remoto",
    "ui.conflictos.aplicar_opcion_seleccionada": "Aplicar opción seleccionada",
    "ui.conflictos.siguiente_conflicto": "Siguiente conflicto",
    "ui.conflictos.resolver_todos_automaticamente": "Resolver todos automáticamente (según política por defecto)",
    "ui.conflictos.sin_conflictos": "Sin conflictos.",
    "ui.conflictos.resumen_conflictos_resueltos": "Resumen: Conflictos resueltos {resueltos} · Pendientes {pendientes} · Requieren revisión manual {revision_manual}",
    "ui.conflictos.conflicto_pendiente_reintentar": "Conflicto pendiente. Reintenta la sincronización.",
    "ui.conflictos.aplicar_a_todos": "Aplicar a todos",
    "ui.conflictos.confirmacion_aplicar_a_todos": "Se resolverán todos los conflictos con la política activa. ¿Continuar?",
    "ui.conflictos.columna_tipo": "Tipo",
    "ui.conflictos.columna_fecha": "Fecha",
    "ui.conflictos.columna_campo_clave": "Campo clave",
    "ui.conflictos.columna_ultima_edicion_local": "Última edición local",
    "ui.conflictos.columna_ultima_edicion_remota": "Última edición remota",
    "ui.errores.causa_probable_label": "Causa probable:",
    "ui.errores.id_incidente_label": "ID de incidente:",
    "ui.errores.no_se_pudo_completar_operacion": "No se pudo completar la operación",
    "ui.errores.regla_negocio_probable": "Los datos ingresados no cumplen una regla de negocio.",
    "ui.errores.corregir_datos_reintentar": "Corrige los datos marcados y reintenta.",
    "ui.errores.no_fue_posible_acceder_datos": "No fue posible acceder a los datos o al servicio externo.",
    "ui.errores.reintenta_revision_config_soporte": "Reintenta. Si persiste, revisa la configuración o contacta soporte.",
    "ui.errores.error_inesperado": "Ocurrió un error inesperado.",
    "ui.errores.fallo_tecnico_no_identificado": "Se produjo un fallo técnico no identificado.",
    "ui.errores.reintenta_contacta_soporte": "Reintenta. Si persiste, contacta soporte.",
    "ui.comun.reintentar": "Reintentar",
    "ui.comun.no_disponible": "No disponible",
    "ui.comun.cerrar": "Cerrar",
    # UI validación
    "ui.validacion.solicitud_duplicada": "Solicitud duplicada",
    "ui.validacion.duplicada_pendiente": "Ya existe una solicitud pendiente igual.",
    "ui.validacion.duplicada_pendiente_info": "Puedes ir a la pendiente existente para gestionarla.",
    "ui.validacion.ir_pendiente": "Ir a la pendiente existente",
    "ui.validacion.duplicada_historico": "La solicitud ya está confirmada en histórico.",
    "ui.validacion.duplicada_historico_info": "Puedes abrir el histórico para revisarla.",
    "ui.validacion.ir_historico": "Ir al histórico",
    "ui.validacion.cancelar": "Cancelar",
    "ui.validacion.validacion": "Validación",
    "ui.validacion.sustituir_por_completo": "Hay horas parciales. ¿Sustituirlas por COMPLETO?",
    "ui.validacion.sustituir_por_franja": "Ya existe un COMPLETO. ¿Sustituirlo por esta franja?",
    "ui.validacion.error": "Error",
    "ui.validacion.reintentar_soporte": "Reintentar. Si persiste, contactar con soporte.",
    "ui.validacion.corrige_dato": "Corrige el dato indicado y vuelve a intentarlo.",
    "ui.validacion.no_disponible_abrev": "N/D",
    "ui.validacion.sin_detalle_tecnico": "Sin detalle técnico",
    "ui.validacion.conflicto": "Conflicto",
    "ui.validacion.procesando": "Procesando…",
    # UI toast
    "ui.toast.detalles_notificacion": "Detalles de notificación",
    "ui.toast.copiar": "Copiar",
    "ui.toast.titulo": "Título:",
    "ui.toast.mensaje": "Mensaje:",
    "ui.toast.codigo": "Código:",
    "ui.toast.correlacion": "Correlación:",
    "ui.toast.fecha_hora": "Fecha y hora:",
    "ui.toast.detalles": "Detalles:",
    "ui.toast.timestamp": "Timestamp:",
    "ui.toast.no_disponible": "No disponible",
    "ui.toast.notificacion": "Notificación",
    "ui.toast.fecha_formato_default": "%d/%m/%Y %H:%M:%S",
}


def copy_text(key: str) -> str:
    """Devuelve un texto de UI por clave estable.

    Lanza ``KeyError`` si falta la clave para detectar regresiones en tests.
    """

    return _COPY[key]


def copy_keys() -> tuple[str, ...]:
    """Expone las claves disponibles para validación en tests."""

    return tuple(_COPY.keys())
