from __future__ import annotations

"""Catálogo centralizado de textos de interfaz.

Este módulo evita strings duplicados en widgets y facilita mantenimiento de copy.
Regla práctica para juniors:
- Usa claves estables por subcontexto (ej. ``solicitudes.*``).
- No referencies textos desde la UI de forma hardcoded.
- Si cambias un mensaje, conserva la clave y solo ajusta el valor.
"""

_COPY: dict[str, str] = {
    # Solicitudes
    "solicitudes.section_title": "Solicitudes",
    "solicitudes.subtitle": "Gestiona la operativa diaria de solicitudes con una vista clara y consistente.",
    "solicitudes.form_section_title": "Datos de la reserva",
    "solicitudes.label_delegada": "Delegada",
    "solicitudes.label_fecha": "Fecha",
    "solicitudes.label_desde": "Desde",
    "solicitudes.label_hasta": "Hasta",
    "solicitudes.label_notas": "Notas",
    "solicitudes.placeholder_notas": "Notas para la solicitud",
    "solicitudes.button_add_pending": "Añadir pendiente",
    "solicitudes.button_update_pending": "Actualizar pendiente",
    "solicitudes.button_confirm_without_pdf": "Confirmar sin PDF",
    "solicitudes.button_confirm_with_pdf": "Confirmar y generar PDF",
    "solicitudes.button_pending_delete": "Eliminar selección",
    "solicitudes.pending_errors_title": "Revisa estos puntos antes de continuar",
    "solicitudes.pending_errors_intro": "Falta completar algunos datos. Te indicamos cómo resolverlo:",
    "solicitudes.tooltip_delegada": "Selecciona la delegada para asociar correctamente la solicitud.",
    "solicitudes.tooltip_fecha": "Elige la fecha del permiso sindical que vas a registrar.",
    "solicitudes.tooltip_desde": "Hora de inicio. Ejemplo: 09:00.",
    "solicitudes.tooltip_hasta": "Hora de fin. Debe ser posterior a la hora de inicio.",
    "solicitudes.tooltip_minutos": "Duración calculada automáticamente en formato HH:MM.",
    "solicitudes.tooltip_notas": "Opcional: añade contexto para recordar el motivo.",
    "solicitudes.tip_enter": "Tip: pulsa Enter para guardar más rápido.",
    "solicitudes.tip_minutes": "Tip: 90 minutos equivalen a 1h 30min.",
    "solicitudes.tip_full_day": "Tip: marca 'Completo' cuando sea un día completo.",
    "solicitudes.help_toggle": "Mostrar ayuda",
    "solicitudes.status_ready": "Listo",
    "solicitudes.status_saved": "Guardado",
    "solicitudes.status_pending_sync": "Pendiente de sync",
    "solicitudes.status_error": "Error",
    "solicitudes.status_pending_sync_hint": "Hay cambios guardados localmente que aún no se han enviado a Google Sheets.",
    "solicitudes.validation_delegada": "Falta delegada. Selecciona una para continuar.",
    "solicitudes.validation_fecha": "Fecha inválida. Revisa el día seleccionado.",
    "solicitudes.validation_tramo_prefix": "Tramo horario incompleto.",
    "solicitudes.validation_conflict": "Ya existe un conflicto pendiente en esa fecha. Ajusta fecha o tramo.",
    "solicitudes.validation_blocking_toast": "Revisa los errores marcados y corrígelos para continuar.",
    "solicitudes.no_aplica_completo": "No aplica en solicitud completa",
    "solicitudes.confirm_delete_pending_title": "Confirmar eliminación",
    "solicitudes.confirm_delete_pending_message": "Se eliminará la solicitud pendiente seleccionada. ¿Deseas continuar?",
    "pendientes.toast_undo": "Pendiente deshecha",
    # Sync credenciales
    "sync_credenciales.title": "Asistente de conexión con Google Sheets",
    "sync_credenciales.step_1": "Paso 1 · Qué necesitas",
    "sync_credenciales.step_1_body": "Necesitas el ID/URL de la hoja y un archivo JSON de credenciales de cuenta de servicio.",
    "sync_credenciales.step_2": "Paso 2 · Cargar credenciales",
    "sync_credenciales.step_3": "Paso 3 · Probar conexión",
    "sync_credenciales.step_4": "Paso 4 · Guardar y finalizar",
    "sync_credenciales.spreadsheet_placeholder": "Pega aquí la URL o el ID de la hoja",
    "sync_credenciales.credentials_button": "Seleccionar credenciales JSON…",
    "sync_credenciales.test_connection": "Probar conexión",
    "sync_credenciales.save": "Guardar",
    "sync_credenciales.saved_ok": "Configuración guardada. Ya puedes sincronizar.",
    "sync_credenciales.status_pending": "Pendiente de comprobación",
    "sync_credenciales.status_ok": "Conexión verificada",
    "sync_credenciales.status_credentials_missing": "Credenciales sin seleccionar",
    "sync_credenciales.status_credentials_ok": "Credenciales seleccionadas",
    "sync_credenciales.status_sheet_missing": "Hoja sin configurar",
    "sync_credenciales.status_sheet_ok": "Hoja configurada",
    # UI preferencias
    "ui.preferencias.settings_show_help_key": "ux/mostrar_ayuda",
    "ui.preferencias.saldos_detallados": "Saldos detallados",
    "ui.preferencias.cerrar": "Cerrar",
    "ui.preferencias.confirmacion": "Confirmación",
    "ui.preferencias.solicitudes_confirmadas": "solicitudes confirmadas",
    "ui.preferencias.errores": "errores",
    "ui.preferencias.no_confirmada": "No se pudo confirmar ninguna solicitud",
    "ui.preferencias.validacion_preventiva": "Validación preventiva",
    "ui.preferencias.corregir_errores": "Corrige los errores pendientes antes de añadir.",
    "ui.preferencias.mensual": "Mensual",
    # UI sync
    "ui.sync.preferencias": "Preferencias",
    "ui.sync.maximizada_por_defecto": "Abrir la app maximizada por defecto",
    "ui.sync.google_sheets": "Google Sheets",
    "ui.sync.fuente_placeholder": "Fuente: --",
    "ui.sync.rango_placeholder": "Rango: --",
    "ui.sync.configurar_conexion": "Configurar conexión Google Sheets",
    "ui.sync.probar_conexion": "Probar conexión",
    "ui.sync.sincronizar_ahora": "Sincronizar ahora",
    "ui.sync.configuracion": "Configuración",
    "ui.sync.resumen": "Resumen de sincronización con acciones rápidas. El detalle técnico está en modo avanzado.",
    "ui.sync.estado": "Estado",
    "ui.sync.ultima_sync_placeholder": "Última sync: --",
    "ui.sync.estado_pendiente": "Estado: Pendiente",
    "ui.sync.acciones": "Acciones",
    "ui.sync.simular": "Simular sincronización",
    "ui.sync.reintentar_fallidos": "Reintentar solo fallidos",
    "ui.sync.ver_detalles": "Ver detalles",
    "ui.sync.ocultar_detalles": "Ocultar detalles",
    "ui.sync.copiar_informe": "Copiar informe",
    "ui.sync.abrir_logs": "Abrir carpeta de logs",
    "ui.sync.ver_historial": "Ver historial",
    "ui.sync.revisar_conflictos": "Revisar conflictos",
    "ui.sync.metricas_placeholder": "Duración: -- · Cambios: -- · Conflictos: -- · Errores: --",
    "ui.sync.tendencia_placeholder": "Tendencia (5): --",
    "ui.sync.idempotencia_placeholder": "Evita duplicados: --",
    "ui.sync.resumen_conteos_placeholder": "Resumen: creadas 0 · actualizadas 0 · omitidas 0 · conflictos 0 · errores 0",
    "ui.sync.ir_configuracion": "Ir a configuración",
    "ui.sync.sincronizando": "Sincronizando con Google Sheets…",
    "ui.sync.alertas_sin_activas": "Alertas: sin alertas activas.",
    "ui.sync.conflictos_pendientes": "Hay 0 conflictos pendientes de revisión.",
    "ui.sync.resultado_resumido": "Resultado resumido",
    "ui.sync.panel_avanzado": "Panel avanzado",
    "ui.sync.detalles_tecnicos": "Detalles técnicos",
    "ui.sync.salud_sistema": "Salud del sistema",
    "ui.sync.estado_general_pendiente": "Estado general: pendiente de comprobación",
    "ui.sync.columna_categoria": "Categoría",
    "ui.sync.columna_mensaje": "Mensaje",
    "ui.sync.columna_accion": "Acción",
    "ui.sync.actualizar_salud": "Actualizar salud",
    "ui.sync.no_mostrar_hoy": "No mostrar hoy",
    "ui.sync.tab_sincronizacion": "Sincronización",
    "ui.sync.pendiente_horas": "Pendiente: 00:00",
    "ui.sync.fuente_prefix": "Fuente:",
    "ui.sync.rango_prefix": "Rango:",
    "ui.sync.idempotencia_regla": "Evita duplicados: misma delegada, fecha y tramo",
    "ui.sync.window_title": "Horas Sindicales",
    "ui.sync.qt_no_disponible": "UI no disponible: falta instalación de Qt/PySide6",
    "ui.sync.mainwindow_incompleta": "MainWindow mal inicializada. Falta widget requerido:",
    # UI conflictos
    "ui.conflictos.accion_recomendada_label": "Acción recomendada:",
    "ui.conflictos.solicitud_label": "Solicitud:",
    "ui.conflictos.item_accion_recomendada": "- Acción recomendada:",
    "ui.conflictos.item_delegada_afectada": "- Delegada afectada:",
    "ui.conflictos.item_tipo_conflicto": "- Tipo de conflicto:",
    "ui.conflictos.estado_con_avisos": "· Con avisos",
    "ui.conflictos.estado_pendiente": "· Pendiente",
    "ui.sync.resumen_actualizadas": "Actualizadas en Sheets:",
    "ui.sync.resumen_insertadas": "Insertadas en Sheets:",
    "ui.sync.resumen_omitidas_delegada": "Omitidas por delegada:",
    "ui.sync.resumen_duplicados_omitidos": "Duplicados omitidos:",
    "ui.sync.resumen_conflictos": "Conflictos:",
    "ui.sync.resumen_errores": "Errores:",
    "ui.sync.resumen_ultima_sincronizacion": "Última sincronización:",
    "ui.sync.bullet_conflictos": "· Conflictos:",
    "ui.sync.bullet_errores": "· Errores:",
    "ui.sync.bullet_filas_actualizadas": "· Filas actualizadas:",
    "ui.sync.bullet_filas_omitidas": "· Filas omitidas:",
    # UI validación
    "ui.validacion.solicitud_duplicada": "Solicitud duplicada",
    "ui.validacion.duplicada_pendiente": "Ya existe una solicitud pendiente igual.",
    "ui.validacion.duplicada_pendiente_info": "Puedes ir a la pendiente existente para gestionarla.",
    "ui.validacion.ir_pendiente": "Ir a la pendiente existente",
    "ui.validacion.duplicada_historico": "La solicitud ya está confirmada en histórico.",
    "ui.validacion.duplicada_historico_info": "Puedes abrir el histórico para revisarla.",
    "ui.validacion.ir_historico": "Ir al histórico",
    "ui.validacion.cancelar": "Cancelar",
    "ui.validacion.validacion": "Validación",
    "ui.validacion.sustituir_por_completo": "Hay horas parciales. ¿Sustituirlas por COMPLETO?",
    "ui.validacion.sustituir_por_franja": "Ya existe un COMPLETO. ¿Sustituirlo por esta franja?",
    "ui.validacion.error": "Error",
    "ui.validacion.reintentar_soporte": "Reintentar. Si persiste, contactar con soporte.",
    "ui.validacion.corrige_dato": "Corrige el dato indicado y vuelve a intentarlo.",
    "ui.validacion.no_disponible_abrev": "N/D",
    "ui.validacion.sin_detalle_tecnico": "Sin detalle técnico",
    "ui.validacion.conflicto": "Conflicto",
    "ui.validacion.procesando": "Procesando…",
    # UI toast
    "ui.toast.detalles_notificacion": "Detalles de notificación",
    "ui.toast.copiar": "Copiar",
    "ui.toast.titulo": "Título:",
    "ui.toast.mensaje": "Mensaje:",
    "ui.toast.codigo": "Código:",
    "ui.toast.correlacion": "Correlación:",
    "ui.toast.fecha_hora": "Fecha y hora:",
    "ui.toast.detalles": "Detalles:",
    "ui.toast.timestamp": "Timestamp:",
    "ui.toast.no_disponible": "No disponible",
    "ui.toast.notificacion": "Notificación",
    "ui.toast.fecha_formato_default": "%d/%m/%Y %H:%M:%S",
}


def copy_text(key: str) -> str:
    """Devuelve un texto de UI por clave estable.

    Lanza ``KeyError`` si falta la clave para detectar regresiones en tests.
    """

    return _COPY[key]


def copy_keys() -> tuple[str, ...]:
    """Expone las claves disponibles para validación en tests."""

    return tuple(_COPY.keys())
